# Generated by Django 6.0.4 on 2026-05-02 12:43

import apps.itinerary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_lkr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('group_size', models.PositiveSmallIntegerField(default=1)),
                ('group_type', models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('group', 'Group')], default='solo', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('shared', 'Shared')], default='draft', max_length=10)),
                ('share_token', models.CharField(default=apps.itinerary.models._new_share_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attractions.district')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary.itinerary')),
            ],
            options={
                'db_table': 'itinerary_days',
                'ordering': ['itinerary_id', 'day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveSmallIntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('duration_mins', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tip', models.TextField(blank=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='itinerary.itineraryday')),
            ],
            options={
                'db_table': 'itinerary_stops',
                'ordering': ['day_id', 'stop_order'],
            },
        ),
    ]
