# Generated by Django 5.1.15 on 2026-05-02 07:28

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, default=apps.core.models._new_session_token, max_length=128, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('si', 'Sinhala'), ('ta', 'Tamil')], default='en', max_length=2)),
                ('budget_range', models.CharField(blank=True, max_length=32)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-updated_at'],
            },
        ),
    ]
