# Generated by Django 5.1.15 on 2026-05-02 07:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('climate_zone', models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry'), ('intermediate', 'Intermediate')], default='wet', max_length=16)),
                ('peak_months', models.JSONField(blank=True, default=list)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['province'], name='districts_provinc_024f4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('wildlife', 'Wildlife'), ('cultural', 'Cultural'), ('religious', 'Religious'), ('adventure', 'Adventure'), ('food', 'Food')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('entry_fee_lkr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('best_season', models.JSONField(blank=True, default=list)),
                ('crowd_index', models.PositiveSmallIntegerField(default=5, help_text='Steady-state crowd level (1 quiet → 10 packed).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('trend_score', models.FloatField(default=0.0)),
                ('chroma_doc_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='attractions.district')),
            ],
            options={
                'db_table': 'attractions',
                'ordering': ['-trend_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('s3_key', models.CharField(max_length=500)),
                ('cdn_url', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('caption', models.TextField(blank=True)),
                ('attribution', models.CharField(blank=True, max_length=300)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='attractions.attraction')),
            ],
            options={
                'db_table': 'media_assets',
                'ordering': ['-is_featured', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['category'], name='attractions_categor_b26c08_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['district'], name='attractions_distric_2540d5_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['-trend_score'], name='attractions_trend_s_2dc5db_idx'),
        ),
    ]
