# Generated by Django 5.1.15 on 2026-05-02 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google', 'Google'), ('reddit', 'Reddit'), ('twitter', 'Twitter / X'), ('manual', 'Manual')], max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='attractions.attraction')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-ingested_at'],
                'indexes': [models.Index(fields=['attraction', '-ingested_at'], name='reviews_attract_7fb360_idx'), models.Index(fields=['sentiment_label'], name='reviews_sentime_740abe_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uq_review_source_external_id')],
            },
        ),
    ]
