"""ReportLab-powered PDF rendering for itineraries."""

from __future__ import annotations

import io
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


JADE = colors.HexColor("#0F3C2E")
SAFFRON = colors.HexColor("#E89D1C")
INK = colors.HexColor("#1A1A1A")


def render_itinerary_pdf(itinerary) -> bytes:
    """Returns the PDF bytes for the given Itinerary instance."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title=itinerary.title or f"LankaGuide itinerary #{itinerary.id}",
        author="LankaGuide",
    )
    styles = _styles()
    story: list = []

    story.append(Paragraph("LANKAGUIDE", styles["kicker"]))
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(itinerary.title or f"Itinerary #{itinerary.id}", styles["title"])
    )
    story.append(Spacer(1, 4))
    story.append(
        Paragraph(
            f"{itinerary.start_date} &mdash; {itinerary.end_date} &middot; "
            f"{(itinerary.end_date - itinerary.start_date).days + 1} days &middot; "
            f"{itinerary.group_size} traveller(s) ({itinerary.group_type})",
            styles["lead"],
        )
    )
    if itinerary.budget_lkr:
        story.append(
            Paragraph(
                f"Budget guide: LKR {itinerary.budget_lkr:,.0f}", styles["lead"]
            )
        )
    story.append(Spacer(1, 18))

    days = list(itinerary.days.prefetch_related("stops__attraction").order_by("day_number"))
    for day in days:
        story.append(
            Paragraph(
                f"Day {day.day_number} — {day.district.name if day.district else 'Sri Lanka'}",
                styles["day"],
            )
        )
        if day.notes:
            story.append(Paragraph(day.notes, styles["day_notes"]))

        rows: list = [["#", "Stop", "Time", "Duration", "Tip"]]
        for stop in day.stops.all():
            time_str = stop.arrival_time.strftime("%H:%M") if stop.arrival_time else "—"
            duration = f"{stop.duration_mins or '—'} min" if stop.duration_mins else "—"
            rows.append([
                str(stop.stop_order),
                stop.attraction.name,
                time_str,
                duration,
                stop.tip or "",
            ])

        if len(rows) > 1:
            tbl = Table(
                rows,
                colWidths=[1 * cm, 5 * cm, 2 * cm, 2.5 * cm, 6 * cm],
                hAlign="LEFT",
            )
            tbl.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), JADE),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 9),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        (
                            "ROWBACKGROUNDS",
                            (0, 1),
                            (-1, -1),
                            [colors.whitesmoke, colors.white],
                        ),
                        ("LINEBELOW", (0, 0), (-1, 0), 0.6, JADE),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ]
                )
            )
            story.append(tbl)
        story.append(Spacer(1, 18))

    story.append(Spacer(1, 12))
    story.append(
        Paragraph(
            "Generated by LankaGuide — your AI travel companion. "
            "Confirm seasonal opening hours, fees, and entry requirements "
            "before each visit.",
            styles["footer"],
        )
    )

    doc.build(story)
    return buffer.getvalue()


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "kicker": ParagraphStyle(
            "kicker",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=SAFFRON,
            letterSpacing=2,
            spaceAfter=2,
        ),
        "title": ParagraphStyle(
            "title",
            parent=base["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=28,
            textColor=JADE,
        ),
        "lead": ParagraphStyle(
            "lead",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=INK,
            spaceAfter=4,
        ),
        "day": ParagraphStyle(
            "day",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=JADE,
            spaceBefore=6,
            spaceAfter=4,
        ),
        "day_notes": ParagraphStyle(
            "day_notes",
            parent=base["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=9.5,
            leading=13,
            textColor=INK,
            spaceAfter=6,
        ),
        "footer": ParagraphStyle(
            "footer",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=INK,
        ),
    }
