# Generated by Django 6.0.4 on 2026-05-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='wikipedia_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attraction',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='district',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='district',
            name='youtube_video_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='attractions.district'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='license',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='cdn_url',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='s3_key',
            field=models.CharField(max_length=600),
        ),
    ]
