# Generated by Django 5.x — SeasonalData model (Gap 8).

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0003_attraction_sentiment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("crowd_index", models.FloatField()),
                (
                    "weather_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("is_peak_season", models.BooleanField(default=False)),
                ("visitor_note", models.CharField(blank=True, max_length=200)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_data",
                        to="attractions.attraction",
                    ),
                ),
            ],
            options={
                "db_table": "attraction_seasonal_data",
                "ordering": ["month"],
                "unique_together": {("attraction", "month")},
            },
        ),
    ]
